#config_version=6

widgets:
  player_up:
  - type: text
    text: "Marinaio (number) Avanti"
    anchor_y: bottom
    anchor_x: left
    y: bottom+23%
    x: left+5%
    # water blue from backglass
    color: blue
    style: medium
    font_size: 72
  ball_count:
  - type: text
    text: "Boccia: (ball)"
    anchor_y: bottom
    anchor_x: right
    y: bottom+23%
    x: right-5%
    # water blue from backglass
    color: red
    style: medium
    font_size: 72
  current_score:
  - type: text
    text: "(score)"
    number_grouping: true # adds commas to integer value display
    min_digits: 2
    anchor_y: middle
    anchor_x: center
    y: middle+15%
    color: yellow
    style: big
    font_size: 180
    animations:
      add_to_slide: pulsate_fast
  p1_score:
  - type: text
    text: "(player1|score)"
    number_grouping: true # adds commas to integer value display
    anchor_y: top
    anchor_x: left
    y: top-5%
    x: left+5%
    min_digits: 2
    color: yellow
    style: big
    font_size: 72
  p2_score:
  - type: text
    text: "(player2|score)"
    number_grouping: true # adds commas to integer value display
    anchor_y: top
    anchor_x: right
    y: top-5%
    x: right-5%
    min_digits: 2
    color: yellow
    style: big
    font_size: 72
  p3_score:
  - type: text
    text: "(player3|score)"
    number_grouping: true # adds commas to integer value display
    anchor_y: bottom
    anchor_x: left
    y: bottom+5%
    x: left+5%
    min_digits: 2
    color: yellow
    style: big
    font_size: 72
  p4_score:
  - type: text
    text: "(player4|score)"
    number_grouping: true # adds commas to integer value display
    anchor_y: bottom
    anchor_x: right
    y: bottom+5%
    x: right-5%
    min_digits: 2
    color: yellow
    style: big
    font_size: 72
  shoot_again:
  - type: text
    text: "Torna in battaglia sailor!"
    style: medium
    font_size: 72
    color: red
    anchor_y: middle
    anchor_x: center
    y: middle-8%
    animations:
      add_to_slide: pulsate_slow
  credits:
  - type: text
    text: "Saved by Pinball Plaid & Death Save Pinball Cult. Music by Flannel. SFX by Raphael."
    style: medium
    font_size: 90
    color: red
    x: -4200
    anchor_y: middle
    anchor_x: center
    y: middle-10%
    animations:
      add_to_slide: wide_scroll_left
  grand_champion:
  - type: text
    text: "(machine|score1_label)    (machine|score1_name): (machine|score1_value)"
    number_grouping: true
    min_digits: 2
    style: medium
    color: blue
    x: -4200
    y: middle-8%
    font_size: 140
    animations:
      add_to_slide: wide_scroll_left
  high_scores:
  - type: text
    text: "(machine|score2_name): (machine|score2_value)   (machine|score3_name): (machine|score3_value)   (machine|score4_name): (machine|score4_value)   (machine|score5_name): (machine|score5_value)"
    number_grouping: true
    min_digits: 2
    style: medium
    color: blue
    x: -4200
    y: middle-10%
    font_size: 100
    animations:
      add_to_slide: wide_scroll_left
  multiball_champions:
  - type: text
    text: "(machine|multiball_score1_label) (machine|multiball_score1_name): (machine|multiball_score1_value)      (machine|multiball_score2_label) (machine|multiball_score2_name): (machine|multiball_score2_value)"
    number_grouping: true
    min_digits: 2
    style: medium
    color: blue
    x: -4200
    y: middle-10%
    font_size: 110
    animations:
      add_to_slide: wide_scroll_left
  title:
  - type: text
    text: "Zaccaria “Combat”"
    style: big
    color: red
    x: -1920
    font_size: 180
    animations:
      add_to_slide: scroll_right
  credit:
  - type: text
    text: "Saved by:"
    style: medium
    color: yellow
    font_size: 120
  company:
  - type: text
    text: "Pinball Plaid and the\nDeath Save Pinball Cult"
    color: blue
    style: small
    font_size: 100
    animations:
      add_to_slide: pulsate_slow
  game_over:
  - type: text
    text: "GAME OVER"
    y: middle+15%
    style: big
    color: red
    font_size: 120
    animations:
      add_to_slide: pulsate_slow
